name: ${project.name}
version: ${project.version}#${git.commit.id.describe}
description: ${project.description}

api-version: "1.13"

author: Coding-Area

main: ${project.groupId}.${project.artifactId}.${project.name}Plugin
