name: Qodana - Code Inspection
on:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v4.2.2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./
          commit_message: Updated Qodana Report ${GITHUB_SHA}